# Generated by Django 3.2.25 on 2024-08-07 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_basket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='productscategory',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
    ]
